services:
  uptime-kuma:
    image: hienhoceo-dpsmedia/uptime-kuma-vn:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
